<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../Libs/Db.class.php';

/**
 * Test class for Db.
 * Generated by PHPUnit on 2009-12-20 at 04:58:52.
 */
class DbTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Db
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Db;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetConnection().
     */
    public function testGetConnection()
    {
        $this->assertTrue( method_exists($this->object, 'getConnection') );
    }

    /**
     * @todo Implement testCall().
     */
    public function testCall()
    {
        $this->assertTrue( method_exists($this->object, 'call') );
    }
}
?>
