<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../Libs/Localidades.class.php';

/**
 * Test class for Localidades.
 * Generated by PHPUnit on 2009-12-20 at 04:58:55.
 */
class LocalidadesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Localidades
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Localidades;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testCidades().
     */
    public function testCidades()
    {
        $this->assertTrue( method_exists($this->object, 'cidades') );
    }

    /**
     * @todo Implement testEstados().
     */
    public function testEstados()
    {
        $this->assertTrue( method_exists($this->object, 'estados') );
    }

    /**
     * @todo Implement testPaises().
     */
    public function testPaises()
    {
        $this->assertTrue( method_exists($this->object, 'paises') );
    }
}
?>
